---
- hosts: all
  roles:
    # - johncming.emacs
    - johncming.go

- hosts: all
  tasks:
    - blockinfile:
        path: "{{ ansible_user_dir }}/.terraformrc"
        create: yes
        block: |
          providers {
              mydns = "/vagrant/"
          }

    - file:
        path: "{{ ansible_user_dir}}/.go/src/github.com/johncming/"
        state: directory

    - file:
        src: /vagrant
        dest: "{{ ansible_user_dir}}/.go/src/github.com/johncming/terraform-provider-mydns"
        state: link
