---
- hosts: all
  roles:
    # - johncming.emacs
    - johncming.go

- hosts: all
  tasks:
    - blockinfile:
        path: "{{ ansible_user_dir }}/.terraformrc"
        create: yes
        block: |
          providers {
              mydns = "/vagrant/"
          }
